services:
  app:
    image: ghcr.io/stonek79/knock-knock-app:latest
    container_name: knock-knock-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
